local Translations = {
	["提示"] = { ["en"] = "Tips" },

	["主页"] = { ["en"] = "Home Tab" },
	["加速等功能在通用内 部分游戏需在局内加载"] = { ["en"] = "Speed Hack and other features are in the General tab, some games require loading in the game" },
	["通用"] = { ["en"] = "General" },
	["玩家"] = { ["en"] = "Players" },
	["速度"] = { ["en"] = "Speed" },
	["加速"] = { ["en"] = "Speed Hack" },
	["穿墙"] = { ["en"] = "Noclip" },
	["飞天"] = { ["en"] = "Fly Jump" },
	["飞行"] = { ["en"] = "Fly" },
	["秒重生"] = { ["en"] = "No Delay Respawn" },
	["角色死后秒重生并回到原点"] = { ["en"] = "Respawn and return to origin after death" },
	["无头"] = { ["en"] = "No Head" },

	["透视"] = { ["en"] = "ESP" },
	["名字血量"] = { ["en"] = "Name and Health" },

	["追踪"] = { ["en"] = "Track" },
	["目标"] = { ["en"] = "Target" },
	["位置"] = { ["en"] = "Position" },
	["背后"] = { ["en"] = "Back" },
	["转圈"] = { ["en"] = "Spin" },
	["跟踪偏移"] = { ["en"] = "Offset" },
	["忽略好友"] = { ["en"] = "Ignore Friends" },
	["自动转向"] = { ["en"] = "Auto Rotation" },

	["自瞄"] = { ["en"] = "Aimbot" },
	["顺滑度"] = { ["en"] = "Smoothness" },
	["距离"] = { ["en"] = "Distance" },
	["范围"] = { ["en"] = "Range" },
	["部位"] = { ["en"] = "Part" },
	["按键"] = { ["en"] = "Key" },
	["判断障碍"] = { ["en"] = "Wall Cheak" },
	["忽略队友"] = { ["en"] = "Ignore Teammates" },
	["自动瞄准"] = { ["en"] = "Aimbot" },
	["手机自瞄"] = { ["en"] = "Mobile Aimbot" },
	["瞄准范围"] = { ["en"] = "Aim Range" },
	["判断障碍"] = { ["en"] = "Check Obstacles" },
	["只锁定可视的敌人"] = { ["en"] = "Only lock visible enemies" },
	["忽略队友"] = { ["en"] = "Ignore Teammates" },
	["忽略同队伍的玩家"] = { ["en"] = "Ignore players on the same team" },
	["手机自瞄"] = { ["en"] = "Mobile Aimbot" },

	["俄亥俄州"] = { ["en"] = "Ohio" },
	["有人使用了印钞机"] = { ["en"] = "Have someone use money print" },
	["有人使用了黄金印钞机"] = { ["en"] = "Have someone use gold money print" },
	["主要"] = { ["en"] = "Main" },
	["打击方式"] = { ["en"] = "Hit Mode" },
	["拳头"] = { ["en"] = "Fist" },
	["武器"] = { ["en"] = "Weapon" },
	["护甲种类"] = { ["en"] = "Armor Type" },
	["小型"] = { ["en"] = "Small" },
	["中型"] = { ["en"] = "Medium" },
	["警察"] = { ["en"] = "Police" },
	["重型"] = { ["en"] = "Heavy" },
	["军用"] = { ["en"] = "Military" },
	["EOD"] = { ["en"] = "EOD" },
	["子追RPG模式"] = { ["en"] = "RPG Tracking Mode" },
	["秒全服(危险)"] = { ["en"] = "Instant Kill (Dangerous)" },
	["无视好友"] = { ["en"] = "Ignore Friends" },
	["全功能无视好友"] = { ["en"] = "Ignore friends for all functions" },
	["轰炸内容"] = { ["en"] = "Bombardment Content" },
	["短信轰炸"] = { ["en"] = "SMS Bombardment" },
	["全枪子追"] = { ["en"] = "All Guns Tracking" },
	["打击光环"] = { ["en"] = "Hit Aura" },
	["踩踏光环"] = { ["en"] = "Stomp Aura" },
	["携带光环"] = { ["en"] = "Carry Aura" },
	["自动回血"] = { ["en"] = "Auto Heal" },
	["自动穿甲"] = { ["en"] = "Auto Wear Armor" },
	["自动买甲穿甲"] = { ["en"] = "Auto buy and wear armor" },
	["不会坐下"] = { ["en"] = "No Sitting" },
	["角色不会坐下"] = { ["en"] = "Character won't sit" },
	["赚钱"] = { ["en"] = "Farm" },
	["自动存贵重珠宝"] = { ["en"] = "Auto Stash Valuables" },
	["自动存到保险柜"] = { ["en"] = "Auto stash to safe" },
	["自动制作"] = { ["en"] = "Auto Craft" },
	["自动制作领取罗利"] = { ["en"] = "Auto craft and claim Rollie" },
	["自动面罩"] = { ["en"] = "Auto Mask" },
	["自动面罩(隐藏名字)"] = { ["en"] = "Auto mask (hide name)" },
	["透视物品"] = { ["en"] = "Item ESP" },
	["显示物品名称标签"] = { ["en"] = "Show item name tags" },
	["清理垃圾物品"] = { ["en"] = "Clean Junk Items" },
	["自动删除背包垃圾物品"] = { ["en"] = "Auto delete junk items in backpack" },
	["互动光环"] = { ["en"] = "Interaction Aura" },
	["靠近自动按按钮(部分)"] = { ["en"] = "Auto press buttons when near (some)" },
	["物品光环"] = { ["en"] = "Item Aura" },
	["靠近自动捡物品"] = { ["en"] = "Auto pick up items when near" },
	["现金光环"] = { ["en"] = "Cash Aura" },
	["靠近自动捡现金"] = { ["en"] = "Auto pick up cash when near" },
	["获取零件"] = { ["en"] = "Get Parts" },
	["自动捡零件盒"] = { ["en"] = "Auto pick up part boxes" },
	["自动银行"] = { ["en"] = "Auto Bank" },
	["自动ATM"] = { ["en"] = "Auto ATM" },
	["传送并攻击ATM"] = { ["en"] = "Teleport and attack ATM" },
	["获取现金"] = { ["en"] = "Get Cash" },
	["自动瞬移大于100的现金"] = { ["en"] = "Auto teleport to cash over 100" },
	["获取物品"] = { ["en"] = "Get Items" },
	["自动捡稀有物品(印钞机等)"] = { ["en"] = "Auto pick up rare items (money printers etc.)" },
	["自动隐藏"] = { ["en"] = "Auto Hide" },
	["传送"] = { ["en"] = "Teleport" },
	["印钞机"] = { ["en"] = "Money Printer" },
	["瞬移已使用的印钞机"] = { ["en"] = "Teleport to used money printers" },
	["小保险"] = { ["en"] = "Small Safe" },
	["瞬移过去并打开"] = { ["en"] = "Teleport and open" },
	["中保险"] = { ["en"] = "Medium Safe" },
	["大保险"] = { ["en"] = "Large Safe" },
	["黑保险"] = { ["en"] = "Black Safe" },
	["金保险"] = { ["en"] = "Gold Safe" },
	["小宝箱"] = { ["en"] = "Small Chest" },
	["大宝箱"] = { ["en"] = "Large Chest" },
	["宝藏"] = { ["en"] = "Treasure" },
	["瞬移过去(需手持藏宝图)"] = { ["en"] = "Teleport (need to hold treasure map)" },
	["空投"] = { ["en"] = "Airdrop" },
	["圣诞空投"] = { ["en"] = "Christmas Airdrop" },
	["其他"] = { ["en"] = "Other" },
	["全服抖腿"] = { ["en"] = "Server Shake" },
	["让所有人抖起来(忽略好友可控制)"] = {
		["en"] = "Make everyone shake (controllable by ignoring friends)",
	},
	["制作界面"] = { ["en"] = "Crafting Interface" },
	["工作台制作界面"] = { ["en"] = "Workbench crafting interface" },
	["选择动画"] = { ["en"] = "Select Animation" },
	["选择物品"] = { ["en"] = "Select Item" },
	["射线枪"] = { ["en"] = "Raygun" },
	["购买物品"] = { ["en"] = "Buy Item" },
	["购买所选物品(需要刷新物品状态才会显示 例如枪械买弹药需要装填弹药才显示)"] = {
		["en"] = "Buy selected item (need to refresh item state to show, e.g. guns need to reload ammo to show)",
	},
	["传送地点"] = { ["en"] = "Teleport Location" },
	["雪崩图腾"] = { ["en"] = "Avalanche Totem" },
	["日蚀图腾"] = { ["en"] = "Eclipse Totem" },
	["陨石图腾"] = { ["en"] = "Meteor Totem" },
	["钟表图腾"] = { ["en"] = "Clock Totem" },
	["顺风图腾"] = { ["en"] = "Tailwind Totem" },
	["极光图腾"] = { ["en"] = "Aurora Totem" },
	["风暴图腾"] = { ["en"] = "Storm Totem" },
	["鹿木岛鱼竿"] = { ["en"] = "Deerwood Island Rod" },
	["稿子"] = { ["en"] = "Pickaxe" },
	["三叉戟"] = { ["en"] = "Trident" },
	["深渊竿蓝遗物"] = { ["en"] = "Abyss Rod Blue Relic" },
	["深渊竿红遗物"] = { ["en"] = "Abyss Rod Red Relic" },
	["深渊竿"] = { ["en"] = "Abyss Rod" },
	["天堂竿红水晶按钮1"] = { ["en"] = "Heaven Rod Red Crystal Button 1" },
	["天堂竿红水晶按钮2"] = { ["en"] = "Heaven Rod Red Crystal Button 2" },
	["天堂竿红水晶按钮3"] = { ["en"] = "Heaven Rod Red Crystal Button 3" },
	["天堂竿红水晶按钮4"] = { ["en"] = "Heaven Rod Red Crystal Button 4" },
	["天堂竿红水晶按钮5"] = { ["en"] = "Heaven Rod Red Crystal Button 5" },
	["天堂竿绿水晶"] = { ["en"] = "Heaven Rod Green Crystal" },
	["天堂竿蓝水晶"] = { ["en"] = "Heaven Rod Blue Crystal" },
	["天堂竿黄水晶"] = { ["en"] = "Heaven Rod Yellow Crystal" },
	["天堂竿红水晶"] = { ["en"] = "Heaven Rod Red Crystal" },
	["天堂竿"] = { ["en"] = "Heaven Rod" },
	["深渊幽灵竿"] = { ["en"] = "Abyss Ghost Rod" },
	["鹿木岛"] = { ["en"] = "Deerwood Island" },
	["罗斯利特湾"] = { ["en"] = "Roslit Bay" },
	["被遗弃的岛"] = { ["en"] = "Abandoned Island" },
	["远古岛"] = { ["en"] = "Ancient Island" },
	["亚特兰蒂斯"] = { ["en"] = "Atlantis" },
	["特拉平岛"] = { ["en"] = "Trapin Island" },
	["荒凉深渊"] = { ["en"] = "Desolate Abyss" },
	["附魔祭坛"] = { ["en"] = "Enchantment Altar" },
	["头晕"] = { ["en"] = "Dizzy" },
	["茂密洞穴"] = { ["en"] = "Dense Cave" },
	["北方探险队山顶"] = { ["en"] = "Northern Expedition Peak" },
	["第三区"] = { ["en"] = "Zone 3" },
	["第四区"] = { ["en"] = "Zone 4" },
	["巨齿鲨"] = { ["en"] = "Megalodon" },
	["大白鲨"] = { ["en"] = "Great White Shark" },
	["鲸鲨"] = { ["en"] = "Whale Shark" },
	["抛竿力度"] = { ["en"] = "Cast Power" },
	["自动抛竿的力度(1-100)"] = { ["en"] = "Auto cast power (1-100)" },
	["请输入1-100的数字!"] = { ["en"] = "Please enter a number between 1-100!" },
	["自动抛竿"] = { ["en"] = "Auto Cast" },
	["拿着鱼竿时自动抛竿"] = { ["en"] = "Auto cast when holding rod" },
	["自动摇晃"] = { ["en"] = "Auto Shake" },
	["浮漂落水后自动摇晃"] = { ["en"] = "Auto shake after float lands" },
	["自动钓鱼"] = { ["en"] = "Auto Fish" },
	["鱼上钩后自动钓鱼"] = { ["en"] = "Auto fish when fish bites" },
	["即时浮漂"] = { ["en"] = "Instant Float" },
	["抛竿后浮漂立马落水"] = { ["en"] = "Float lands immediately after casting" },
	["冻结坐标"] = { ["en"] = "Freeze Position" },
	["将角色定在原位"] = { ["en"] = "Lock character in place" },
	["自动出售库存"] = { ["en"] = "Auto Sell Inventory" },
	["自动出售库存内符合标准的物品"] = { ["en"] = "Auto sell items in inventory that meet criteria" },
	["自动出售手持"] = { ["en"] = "Auto Sell Held" },
	["自动出售手中符合标准的物品"] = { ["en"] = "Auto sell held items that meet criteria" },
	["物品名字"] = { ["en"] = "Item Name" },
	["自动拿物品的物品名字"] = { ["en"] = "Item name for auto take" },
	["自动拿物品"] = { ["en"] = "Auto Take Item" },
	["自动拿出符合名字的物品(英文名)"] = { ["en"] = "Auto take items matching name (English name)" },
	["自动给物品"] = { ["en"] = "Auto Give Item" },
	["自动将手上的物品给选择的玩家"] = { ["en"] = "Auto give held item to selected player" },
	["被遗弃"] = { ["en"] = "Forsaken" },
	["发电机 进度:"] = { ["en"] = "Generator Progress:" },
	["物品:"] = { ["en"] = "Item:" },
	["透视对象"] = { ["en"] = "ESP Objects" },
	["发电机 幸存者 杀手 物品"] = { ["en"] = "Generators, Survivors, Killers, Items" },
	["最大体力值"] = { ["en"] = "Max Stamina" },
	["奔跑速度"] = { ["en"] = "Run Speed" },
	["冲刺体力消耗(秒)"] = { ["en"] = "Sprint Stamina Drain (sec)" },
	["停止时恢复体力(秒)"] = { ["en"] = "Stamina Regen When Stopped (sec)" },
	["自动1x1窗口"] = { ["en"] = "Auto 1x1 Window" },
	["自动做1x1窗口"] = { ["en"] = "Auto do 1x1 window" },
	["抛硬币费用"] = { ["en"] = "Coin Flip Cost" },
	["自动抛硬币"] = { ["en"] = "Auto Coin Flip" },
	["修机时间"] = { ["en"] = "Repair Time" },
	["修机次数"] = { ["en"] = "Repair Count" },
	["自动修机"] = { ["en"] = "Auto Repair" },
	["看人距离"] = { ["en"] = "Look Distance" },
	["砍人距离"] = { ["en"] = "Attack Distance" },
	["自动砍人"] = { ["en"] = "Auto Attack" },
	["杀手自动砍人"] = { ["en"] = "Killer auto attacks" },
	["力量传奇"] = { ["en"] = "Muscle Legends" },
	["锻炼类型"] = { ["en"] = "Exercise Type" },
	["跑步机类型"] = { ["en"] = "Treadmill Type" },
	["卡宠石头"] = { ["en"] = "Pet Lock Stone" },
	["刷头模式"] = { ["en"] = "Head Farming Mode" },
	["金宠购买"] = { ["en"] = "Golden Pet Purchase" },
	["自动吃食"] = { ["en"] = "Auto Eat" },
	["自动锻炼"] = { ["en"] = "Auto Exercise" },
	["自动跑步"] = { ["en"] = "Auto Run" },
	["自动重生"] = { ["en"] = "Auto Rebirth" },
	["自动挥拳"] = { ["en"] = "Auto Punch" },
	["石头卡宠"] = { ["en"] = "Stone Pet Lock" },
	["挥拳速度不要太低"] = { ["en"] = "Don't set punch speed too low" },
	["自动刷头"] = { ["en"] = "Auto Head Farm" },
	["自动击杀玩家(默认不杀好友)"] = { ["en"] = "Auto kill players (ignores friends by default)" },
	["挥拳速度"] = { ["en"] = "Punch Speed" },
	["调节挥拳速度(别装备拳头)"] = { ["en"] = "Adjust punch speed (don't equip fists)" },
	["犯罪"] = { ["en"] = "Criminality" },
	["透视黑商"] = { ["en"] = "Black Market ESP" },
	["透视垃圾"] = { ["en"] = "Junk ESP" },
	["透视保险"] = { ["en"] = "Insurance ESP" },
	["种植花园"] = { ["en"] = "Farming Garden" },
	["收菜光环"] = { ["en"] = "Harvest Aura" },
	["靠近菜自动收"] = { ["en"] = "Auto harvest when near crops" },
	["出售光环"] = { ["en"] = "Sell Aura" },
	["靠近出售点自动出售"] = { ["en"] = "Auto sell when near sell point" },
	["自动出售"] = { ["en"] = "Auto Sell" },
	["传送到出售点"] = { ["en"] = "TP to sell" },
	["蜂群模拟器"] = { ["en"] = "Bee Swarm Simulator" },
	["自动采集"] = { ["en"] = "Auto Collect" },
	["静态采集"] = { ["en"] = "Static collection" },
	["自动代币(凝露 票券等)"] = { ["en"] = "Auto Tokens (Nectar, Tickets etc.)" },
	["自动凝露 票券等固定代币"] = { ["en"] = "Auto nectar, tickets and other fixed tokens" },
	["自动找贴纸"] = { ["en"] = "Auto Find Stickers" },
	["挂机田地"] = { ["en"] = "Auto Farm Field" },
	["刀刃球"] = { ["en"] = "Blade Ball" },
	["自动格挡"] = { ["en"] = "Auto Parry" },
	["自动格挡球"] = { ["en"] = "Auto Parry Balls" },
	["附身追随球"] = { ["en"] = "Possession Follow Ball" },
	["红圈格挡"] = { ["en"] = "Red Circle Parry" },
	["脑叶"] = { ["en"] = "Tuantus lobotomization branches" },
	["救援光环"] = { ["en"] = "Rescue Aura" },
	["靠近其他玩家静默救援"] = { ["en"] = "Silently rescue nearby players" },
	["恢复状态"] = { ["en"] = "Recovery Status" },
	["随时随处都可回复状态(有点间隔)"] = { ["en"] = "Recover status anytime anywhere (with some delay)" },
	["夜视"] = { ["en"] = "Night Vision" },
	["有时场景很暗所以做了"] = { ["en"] = "Sometimes the scene is dark so added this" },
	["最强战场"] = { ["en"] = "Strongest Battlegrounds" },
	["传送位置"] = { ["en"] = "Teleport Location" },
	["地图"] = { ["en"] = "Map" },
	["山脉"] = { ["en"] = "Mountains" },
	["安全港"] = { ["en"] = "Safe Harbor" },
	["秘密房间1"] = { ["en"] = "Secret Room 1" },
	["秘密房间2"] = { ["en"] = "Secret Room 2" },
	["设置原位"] = { ["en"] = "Set Original Position" },
	["设置原本的位置"] = { ["en"] = "Set original position" },
	["传送原位"] = { ["en"] = "Teleport to Original Position" },
	["传送到原位"] = { ["en"] = "Teleport to original position" },
	["不朝向好友"] = { ["en"] = "Don't Face Friends" },
	["自动朝向不朝向好友"] = { ["en"] = "Auto face away from friends" },
	["自动垃圾桶"] = { ["en"] = "Auto Trash Can" },
	["拾取+传送最近玩家身后+攻击"] = { ["en"] = "Pick up + teleport behind nearest player + attack" },
	["攻击光环"] = { ["en"] = "Attack Aura" },
	["其他玩家靠近自动攻击"] = { ["en"] = "Auto attack when other players approach" },
	["自动战斗"] = { ["en"] = "Auto Combat" },
	["角色自动战斗"] = { ["en"] = "Character auto combat" },
	["自动攻击"] = { ["en"] = "Auto Attack" },
	["角色自动攻击"] = { ["en"] = "Character auto attacks" },
	["自动开大"] = { ["en"] = "Auto Ultimate" },
	["角色自动使用终极"] = { ["en"] = "Character auto uses ultimate" },
	["抓人传虚空"] = { ["en"] = "Grab to Void" },
	["使用英雄猎人角色2技能抓人传送虚空"] = {
		["en"] = "Use hero hunter's 2nd skill to grab and teleport to void",
	},
	["自动垃圾桶"] = { ["en"] = "Auto Trash Can" },
	["角色自动面向并拿垃圾桶"] = { ["en"] = "Character auto faces and picks up trash cans" },
	["取消冲刺后摇"] = { ["en"] = "Cancel Dash Recovery" },
	["m1reset+emotedash 自己把握好距离(手机勿用)"] = {
		["en"] = "m1reset+emotedash manage distance yourself (don't use on mobile)",
	},
	["自动防御"] = { ["en"] = "Auto Defense" },
	["角色自动防御(增强版)"] = { ["en"] = "Character auto defense (enhanced)" },
	["移除定身"] = { ["en"] = "Remove Stun" },
	["角色无定身状态(如攻击4下之后的定身)"] = {
		["en"] = "Character has no stun state (like after 4 hits)",
	},
	["击杀数"] = { ["en"] = "Kill Count" },
	["伪造你的击杀数(仅自己可见)"] = { ["en"] = "Fake your kill count (visible only to yourself)" },
	["总击杀数"] = { ["en"] = "Total Kills" },
	["伪造你的总击杀数(仅自己可见)"] = { ["en"] = "Fake your total kills (visible only to yourself)" },
	["终极战场"] = { ["en"] = "Ultimate Battlegrounds" },
	["功能"] = { ["en"] = "Features" },
	["移除特效"] = { ["en"] = "Remove Effects" },
	["保持防御"] = { ["en"] = "Keep Block" },
	["保持防御快捷键"] = { ["en"] = "Keep Block Hotkey" },
	["假延迟"] = { ["en"] = "Fake Ping" },
	["无战斗状态"] = { ["en"] = "No Combat Time" },
	["大招加时"] = { ["en"] = "Few UltimateTimer" },
	["大招秒变"] = { ["en"] = "InstantTransformation" },
	["攻击无间隔"] = { ["en"] = "NoAttackDelay" },
	["受击无控制"] = { ["en"] = "DisableHitStun" },
	["未击中无卡住"] = { ["en"] = "NoStunOnMiss" },
	["墙打无冷却"] = { ["en"] = "NoWallComboCooldown" },
	["无敌"] = { ["en"] = "God Mode" },
	["一拳倒地"] = { ["en"] = "One Punch Fall" },
	["倒地击飞"] = { ["en"] = "Fall Knockback" },
	["别改攻速"] = { ["en"] = "Melee Speed must is 100" },
	["无冷却"] = { ["en"] = "No Cooldown" },
	["巫师王角色可用"] = { ["en"] = "Sorcerer King Character Available" },
	["无斩杀动画"] = { ["en"] = "DisableFinishers" },
	["冲刺无冷却"] = { ["en"] = "NoDashCooldown" },
	["无跳跃疲劳"] = { ["en"] = "NoJumpFatigue" },
	["冲刺速度"] = { ["en"] = "Dash Speed" },
	["近战速度"] = { ["en"] = "Melee Speed" },
	["暴力"] = { ["en"] = "Rage" },
	["绕过墙打验证"] = { ["en"] = "Bypass Wall Combo Verification" },
	["使你可以在任意时候使用墙打"] = { ["en"] = "Allow wall combo at any time" },
	["绕过近战验证"] = { ["en"] = "Bypass Melee Verification" },
	["使你可以在任意时候使用近战"] = { ["en"] = "Allow melee at any time" },
	["绕过技能验证"] = { ["en"] = "Bypass Skill Verification" },
	["使你可以在任意时候使用技能"] = { ["en"] = "Allow skill use at any time" },
	["无视好友"] = { ["en"] = "Ignore Friends" },
	["功能对好友无效"] = { ["en"] = "Features do not work against friends" },
	["目标类型"] = { ["en"] = "Target Type" },
	["全部"] = { ["en"] = "All" },
	["最近玩家"] = { ["en"] = "Nearest" },
	["假墙(跟随自己)"] = { ["en"] = "Fake Wall (Follow Self)" },
	["循环墙打(需搭配墙打绕过)"] = { ["en"] = "Wall Combo Spam(Requires Bypass)" },
	["墙打光环"] = { ["en"] = "Wall Combo Aura" },
	["墙打光环距离"] = { ["en"] = "Wall Combo Aura Range" },
	["击杀表情"] = { ["en"] = "Kill Emote" },
	["循环击杀表情(选择)"] = { ["en"] = "Kill Emote Spam(Select)" },
	["循环击杀表情(随机)"] = { ["en"] = "Kill Emote Spam(Random)" },
	["击杀表情间隔(秒)"] = { ["en"] = "Kill Emote Spam Delay(Seconds)" },
	["释放次数(击杀表情)"] = { ["en"] = "Kill Emote Spam Release Count" },

	["死铁轨"] = { ["en"] = "Dead Rails" },
	["固定物品"] = { ["en"] = "Fix Items" },
	["固定周围所有物品"] = { ["en"] = "Fix all nearby items" },
	["解除固定"] = { ["en"] = "Unfix Items" },
	["解除固定周围所有物品"] = { ["en"] = "Unfix all nearby items" },
	["收纳物品"] = { ["en"] = "Store Items" },
	["收纳周围的物品"] = { ["en"] = "Store nearby items" },
	["丢物品"] = { ["en"] = "Drop Items" },
	["丢出收纳的所有物品"] = { ["en"] = "Drop all stored items" },
	["第三人称"] = { ["en"] = "Third Person" },
	["开放第三人称(驾驶勿用)"] = { ["en"] = "Enable third person (don't use while driving)" },
	["债券光环"] = { ["en"] = "Bond Aura" },
	["靠近债券静默拾取"] = { ["en"] = "Auto pick up bonds when near" },
	["独角兽提醒"] = { ["en"] = "Unicorn Alert" },
	["生成独角兽提示"] = { ["en"] = "Notify when unicorn spawns" },
	["发现独角兽请留意四周!"] = { ["en"] = "Unicorn spawns!" },
	["显示燃料余量"] = { ["en"] = "Show Fuel" },
	["显示燃料剩余的数量"] = { ["en"] = "Show remaining fuel amount" },
	["透视物品"] = { ["en"] = "Item ESP" },
	["隔墙绘制物品"] = { ["en"] = "Show items through walls" },
	["透视生物"] = { ["en"] = "Creature ESP" },
	["隔墙绘制生物"] = { ["en"] = "Show creatures through walls" },
	["自动挥铲+杀戮光环=自动攻击+范围 全部生物有效但是不会秒杀"] = {
		["en"] = "Auto Shovel + Kill Aura = Auto attack + AoE, works on all creatures but no instant kill",
	},
	["自动挥铲"] = { ["en"] = "Auto Shovel" },
	["自动挥动铲子"] = { ["en"] = "Automatically swing shovel" },
	["杀戮光环"] = { ["en"] = "Kill Aura" },
	["只对部分怪有用例如僵尸"] = { ["en"] = "Only works on some enemies like zombies" },
	["收物光环"] = { ["en"] = "Collect Aura" },
	["拿着袋子自动收集物品"] = { ["en"] = "Auto collect items when holding bag" },
	["静默换弹"] = { ["en"] = "Silent Reload" },
	["无动作自动换弹"] = { ["en"] = "Reload without animation" },
	["自动收纳物品"] = { ["en"] = "Auto Store Items" },
	["选择要自动收纳的物品"] = { ["en"] = "Select items to auto store" },
	["炮塔(机枪)"] = { ["en"] = "Turret (Machine Gun)" },
	["机枪弹药"] = { ["en"] = "Turret Ammo" },
	["绷带"] = { ["en"] = "Bandage" },
	["煤块"] = { ["en"] = "Coal" },
	["金条"] = { ["en"] = "Gold Bar" },
	["吸血鬼刀"] = { ["en"] = "Vampire Knife" },
	["十字架"] = { ["en"] = "Cross" },
	["雕像"] = { ["en"] = "Statue" },
	["杯子"] = { ["en"] = "Cup" },
	["跑步僵尸"] = { ["en"] = "Running Zombie" },
	["行走僵尸"] = { ["en"] = "Walking Zombie" },
	["债券"] = { ["en"] = "Bond" },
	["一键收纳选中物品"] = { ["en"] = "Store Selected Items" },
	["立即收纳所有下拉菜单中选中的物品"] = { ["en"] = "Instantly store all selected items" },
	["传送使用方法"] = { ["en"] = "Teleport Guide" },
	["1.买枪 2.开启穿墙 3.开启自瞄头部 4.开启自动传送 5.打劫匪(如果角色坐在座位,并且土匪刷新开枪了,就成功了) 6.关掉自动传送 7.传送地点"] = {
		["en"] = "1. Buy gun 2. Enable noclip 3. Enable head aimbot 4. Enable auto teleport 5. Shoot bandits (success if character is seated and bandits spawn shooting) 6. Disable auto teleport 7. Teleport",
	},
	["自瞄头部"] = { ["en"] = "Head Aimbot" },
	["自动移动视角到敌人的头"] = { ["en"] = "Auto aim at enemy heads" },
	["穿墙"] = { ["en"] = "Noclip" },
	["使角色能够穿透物体"] = { ["en"] = "Let character pass through objects" },
	["防甩飞"] = { ["en"] = "Anti Fling" },
	["自动传送"] = { ["en"] = "Auto Teleport" },
	["自动传送"] = { ["en"] = "Automatic teleportation" },
	["传送终点"] = { ["en"] = "Teleport to End" },
	["传送角色至终点"] = { ["en"] = "Teleport character to end" },
	["传送狼堡"] = { ["en"] = "Teleport to Wolf Castle" },
	["传送角色至狼堡"] = { ["en"] = "Teleport character to wolf castle" },
	["传送特斯拉实验室"] = { ["en"] = "Teleport to Tesla Lab" },
	["传送角色至特斯拉实验室"] = { ["en"] = "Teleport character to Tesla lab" },
	["传送军营"] = { ["en"] = "Teleport to Military Camp" },
	["传送角色至军营"] = { ["en"] = "Teleport character to military camp" },
	["ST封锁战线"] = { ["en"] = "ST Blockade Front" },
	["移动功能"] = { ["en"] = "Movement" },
	["抽奖功能"] = { ["en"] = "Gacha" },
	["自动杀戮"] = { ["en"] = "Auto Kill" },
	["自动技能"] = { ["en"] = "Auto Skills" },
	["界面控制"] = { ["en"] = "UI Control" },
	["自动瞄准"] = { ["en"] = "Aimbot" },
	["视觉修改"] = { ["en"] = "Visuals" },
	["角色移动类"] = { ["en"] = "Character movement" },
	["皮肤和角色抽奖"] = { ["en"] = "Skin and character gacha" },
	["自动杀戮资源"] = { ["en"] = "Auto kill resources" },
	["自动技能资源"] = { ["en"] = "Auto skill resources" },
	["控制游戏界面显示"] = { ["en"] = "Control game UI display" },
	["自动瞄准生物"] = { ["en"] = "Auto aim at creatures" },
	["皮肤抽奖"] = { ["en"] = "Skin Gacha" },
	["单抽皮肤 10P"] = { ["en"] = "Single skin pull 10P" },
	["执行1次皮肤抽奖"] = { ["en"] = "Perform 1 skin gacha" },
	["十连抽皮肤 100P"] = { ["en"] = "10x skin pull 100P" },
	["执行10次皮肤抽奖"] = { ["en"] = "Perform 10 skin gachas" },
	["幸运单抽皮肤 100P"] = { ["en"] = "Lucky single skin pull 100P" },
	["执行1次幸运皮肤抽奖"] = { ["en"] = "Perform 1 lucky skin gacha" },
	["角色抽奖"] = { ["en"] = "Character Gacha" },
	["单抽角色"] = { ["en"] = "Single character pull" },
	["执行1次角色抽奖 10P"] = { ["en"] = "Perform 1 character gacha 10P" },
	["十连抽角色 100P"] = { ["en"] = "10x character pull 100P" },
	["执行10次角色抽奖"] = { ["en"] = "Perform 10 character gachas" },
	["单抽幸运角色 100P"] = { ["en"] = "Lucky single character pull 100P" },
	["执行1次幸运角色抽奖"] = { ["en"] = "Perform 1 lucky character gacha" },
	["移动速度"] = { ["en"] = "Movement Speed" },
	["启用移速"] = { ["en"] = "Enable Speed" },
	["跳跃高度"] = { ["en"] = "Jump Height" },
	["启用跳跃"] = { ["en"] = "Enable Jump" },
	["启用自动杀戮"] = { ["en"] = "Enable Auto Kill" },
	["启用自动攻击"] = { ["en"] = "Enable Auto Attack" },
	["启用自动传送怪物"] = { ["en"] = "Enable Auto Teleport to Monsters" },
	["模拟按键用大写字母"] = { ["en"] = "Use uppercase letters for simulated keys" },
	["模拟按键1"] = { ["en"] = "Simulate Key 1" },
	["输入按键(如E,Q,S,D)"] = { ["en"] = "Input key (e.g. E,Q,S,D)" },
	["模拟按键1间隔(毫秒)"] = { ["en"] = "Key 1 interval (ms)" },
	["开启模拟按键1"] = { ["en"] = "Enable Key 1" },
	["模拟按键2"] = { ["en"] = "Simulate Key 2" },
	["模拟按键2间隔(毫秒)"] = { ["en"] = "Key 2 interval (ms)" },
	["开启模拟按键2"] = { ["en"] = "Enable Key 2" },
	["模拟按键3"] = { ["en"] = "Simulate Key 3" },
	["模拟按键3间隔(毫秒)"] = { ["en"] = "Key 3 interval (ms)" },
	["开启模拟按键3"] = { ["en"] = "Enable Key 3" },
	["模拟按键4"] = { ["en"] = "Simulate Key 4" },
	["模拟按键4间隔(毫秒)"] = { ["en"] = "Key 4 interval (ms)" },
	["开启模拟按键4"] = { ["en"] = "Enable Key 4" },
	["模拟按键5"] = { ["en"] = "Simulate Key 5" },
	["模拟按键5间隔(毫秒)"] = { ["en"] = "Key 5 interval (ms)" },
	["开启模拟按键5"] = { ["en"] = "Enable Key 5" },
	["模拟按键6"] = { ["en"] = "Simulate Key 6" },
	["模拟按键6间隔(毫秒)"] = { ["en"] = "Key 6 interval (ms)" },
	["开启模拟按键6"] = { ["en"] = "Enable Key 6" },
	["模拟按键7"] = { ["en"] = "Simulate Key 7" },
	["模拟按键7间隔(毫秒)"] = { ["en"] = "Key 7 interval (ms)" },
	["开启模拟按键7"] = { ["en"] = "Enable Key 7" },
	["局内商店界面"] = { ["en"] = "In-game Shop UI" },
	["局外库存界面"] = { ["en"] = "Out-game Inventory UI" },
	["回到出生点"] = { ["en"] = "Return to Spawn" },
	["回去后可挂机 改角色等"] = { ["en"] = "Can AFK or change character after returning" },
	["自瞄UI"] = { ["en"] = "Aimbot UI" },
	["创建自瞄按钮"] = { ["en"] = "Create aimbot button" },
	["高亮怪物"] = { ["en"] = "Highlight Monsters" },
	["河北唐县"] = { ["en"] = "Hebei Tang County" },
	["默认所有按钮秒按加距离"] = { ["en"] = "Default all buttons instant press + range" },
	["刷钱"] = { ["en"] = "Money Farm" },
	["选Teawen Barista职业"] = { ["en"] = "Choose Teawen Barista job" },
	["活到七天(大厅)"] = { ["en"] = "Survive 7 Days (Lobby)" },
	["免胜场"] = { ["en"] = "Win Requirement Bypass" },
	["活到七天(森林)"] = { ["en"] = "Survive 7 Days (Forest)" },
	["怪物颜色"] = { ["en"] = "Monster Color" },
	["设置绘制怪物颜色"] = { ["en"] = "Set monster highlight color" },
	["透视怪物"] = { ["en"] = "Monster ESP" },
	["隔墙显示怪物"] = { ["en"] = "Show monsters through walls" },
	["无限火力"] = { ["en"] = "Infinite Ammo" },
	["先手持枪械"] = { ["en"] = "Must hold weapon first" },
	["杀戮光环(怪物)"] = { ["en"] = "Kill Aura (Monsters)" },
	["杀戮光环(鹿)"] = { ["en"] = "Kill Aura (Deer)" },
	["自动砍树"] = { ["en"] = "Auto Chop Trees" },
	["先拿斧头"] = { ["en"] = "Must hold axe first" },
	["木头光环"] = { ["en"] = "Wood Aura" },
	["靠近木头静默收集"] = { ["en"] = "Auto collect wood when near" },
	["浆果光环"] = { ["en"] = "Berry Aura" },
	["靠近浆果静默收集"] = { ["en"] = "Auto collect berries when near" },
	["鹿肉光环"] = { ["en"] = "Venison Aura" },
	["靠近鹿肉静默收集"] = { ["en"] = "Auto collect venison when near" },
	["零件光环"] = { ["en"] = "Parts Aura" },
	["靠近零件静默收集"] = { ["en"] = "Auto collect parts when near" },
	["自动零件"] = { ["en"] = "Auto Parts" },
	["循环传送领取零件"] = { ["en"] = "Teleport loop to collect parts" },
	["自动吃食物"] = { ["en"] = "Auto Eat" },
	["需物品栏有食物 饥饿值过半自动吃(部分食物可能没用)"] = {
		["en"] = "Requires food in inventory, auto eats when hunger below 50% (some foods may not work)",
	},
	["收集鹿肉"] = { ["en"] = "Collect Venison" },
	["传送小屋"] = { ["en"] = "Teleport to Cabin" },
	["传送到小屋"] = { ["en"] = "Teleport to cabin" },
	["传送坠机"] = { ["en"] = "Teleport to Crash Site" },
	["传送到坠机事件"] = { ["en"] = "Teleport to plane crash event" },
	["查克拉战场"] = { ["en"] = "Chakra Battlefield" },
	["自动朝向"] = { ["en"] = "Auto Face" },
	["朝向最近的人(距离40)"] = { ["en"] = "Face nearest player (40m range)" },
	["无限侧闪"] = { ["en"] = "Infinite Dash" },
	["角色可以一直侧闪"] = { ["en"] = "Remove dash cooldown" },
	["大便模拟器"] = { ["en"] = "Poop Simulator" },
	["大便"] = { ["en"] = "Auto Poop" },
	["循环大便"] = { ["en"] = "Continuous poop loop" },
	["放屁"] = { ["en"] = "Auto Fart" },
	["循环放屁"] = { ["en"] = "Continuous fart loop" },
	["清除大便和屁"] = { ["en"] = "Cleanup" },
	["循环清除大便和屁"] = { ["en"] = "Auto clean poop/farts" },
	["蓝色锁:对手"] = { ["en"] = "Blue Lock: Opponents" },
	["无限体力"] = { ["en"] = "Infinite Stamina" },
	["奔跑无需体力"] = { ["en"] = "Run without stamina drain" },
	["踢爆足球"] = { ["en"] = "Super Kick" },
	["一脚踢爆足球"] = { ["en"] = "Kick ball with max force" },
	["干扰对手"] = { ["en"] = "Disrupt Opponents" },
	["自动流动"] = { ["en"] = "Auto Flow State" },
	["自动觉醒"] = { ["en"] = "Auto Awaken" },
	["自动射门"] = { ["en"] = "Auto Shoot" },
	["瞄准球"] = { ["en"] = "Ball Aim" },
	["自动瞄准球"] = { ["en"] = "Auto aim at ball" },
	["团队配合"] = { ["en"] = "Team Play" },
	["英雄战场"] = { ["en"] = "Hero Battlefield" },
	["抓人传虚空"] = { ["en"] = "Void Grab" },
	["全角色抓取传送虚空"] = { ["en"] = "Grab and teleport enemies to void" },
	["无限布娃娃"] = { ["en"] = "No Ragdoll" },
	["倒地后可无限使用闪避起身"] = { ["en"] = "Unlimited dodge recovery" },
	["无限冲刺"] = { ["en"] = "Infinite Dash" },
	["动画速度"] = { ["en"] = "Animation Speed" },
	["越高越快"] = { ["en"] = "Higher = faster" },
	["躲避(Evade)"] = { ["en"] = "Evade" },
	["绘制怪物"] = { ["en"] = "Monster ESP" },
	["绘制怪物的位置"] = { ["en"] = "Show monster locations" },
	["自动连跳"] = { ["en"] = "Bunny Hop" },
	["在地面时自动连续跳跃"] = { ["en"] = "Auto jump when grounded" },
	["自动投票"] = { ["en"] = "Auto Vote" },
	["地图全随机投票"] = { ["en"] = "Random map votes" },
	["刷分挂机"] = { ["en"] = "AFK Farm" },
	["战争大亨"] = { ["en"] = "War Tycoon" },
	["传送"] = { ["en"] = "Teleport" },
	["捕捉点"] = { ["en"] = "Capture Point" },
	["断桥1"] = { ["en"] = "Broken Bridge 1" },
	["断桥2"] = { ["en"] = "Broken Bridge 2" },
	["断桥3"] = { ["en"] = "Broken Bridge 3" },
	["空投"] = { ["en"] = "Airdrop" },
	["隐身"] = { ["en"] = "Invisibility" },
	["删业主门"] = { ["en"] = "Remove Doors" },
	["移除跌伤"] = { ["en"] = "No Fall Damage" },
	["武器增强"] = { ["en"] = "Weapon Buff" },
	["无敌模式"] = { ["en"] = "God Mode" },
	["高亮模式"] = { ["en"] = "Highlight Mode" },
	["头部光源"] = { ["en"] = "Head Light" },
	["光源范围"] = { ["en"] = "Light Range" },
	["光源范围(1-60)"] = { ["en"] = "Range (1-60)" },
	["隐藏脚步声"] = { ["en"] = "Mute Steps" },
	["互动光环"] = { ["en"] = "Interaction Aura" },
	["虚假电机信号"] = { ["en"] = "Fake Signals" },
	["自动修复电路"] = { ["en"] = "Auto Repair" },
	["自动吃糖回血"] = { ["en"] = "Auto Heal" },
	["怪物提示"] = { ["en"] = "Monster Alerts" },
	["门透视"] = { ["en"] = "Door ESP" },
}

local player = game:GetService("Players").LocalPlayer
local languageCode = player.LocaleId:sub(1, 2) or "en"
local forcedLanguage = nil

local function T(text)
    local lang = forcedLanguage or languageCode
    return (Translations[text] and Translations[text][lang]) or text
end

return {
    T = T,
    setLanguage = function(lang)
        forcedLanguage = lang
    end
}
